container_path: .
require_root: true
status_file: ./TugBoat/tugboat.json
ignore_folders:

backup: true
backup_path: ./TugBoat/backups/$STACK-NAME
backup_retention: 15
backup_large_mb: 250
backup_large_retention: 5

docker_user:

health_wait: 60

image_check: true
image_check_interval: 60
registry_timeout: 10

icons: true
icon_index_days: 7

manage_cron: true
healthcheck_interval: 1
install_dependencies: true

command_timeout: 0

update_check: true
update_check_interval: 60
auto_update: true
