container_path: /container-data
require_root: true
status_file: ./tugboat.json
ignore_folders:

backup: true
backup_path: /container-data/.backup/$STACK-NAME
backup_retention: 5

docker_user: user
docker_stack_up_cmd: docker compose pull && docker compose up -d && docker image prune -a -f
docker_stack_down_cmd: docker compose down --remove-orphans
docker_stack_start_cmd: docker compose up -d --pull missing
docker_stack_restore_cmd: docker compose up -d --pull missing

health_wait: 60

image_check: true
image_check_interval: 60

command_timeout: 0

update_check: true
auto_update: true

