container_path: /container-data
require_root: true
status_file: /container-data/tugboat.json
ignore_folders:

backup: true
backup_path: /container-data/.backup/$STACK-NAME
backup_retention: 10
backup_large_mb: 0
backup_large_retention: 2

docker_user:

health_wait: 60

image_check: true
image_check_interval: 60

manage_cron: true
install_dependencies: true

command_timeout: 0

update_check: true
auto_update: true
